### ISSUE TITLE
Apple Transport Security seems to break the SDK on iOS9

### ISSUE THREAD

**Issue by tewner** [uservoice/uservoice-ios-sdk#380]
Hi guys!

We're using the UserVoice SDK and I'm researching compatibility with Apple's Transport Security (ATS), part of iOS9.
It seems that UserVoice doesn't work under ATS:

Error (HTTP connection failed): Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSUnderlyingError=0x7fc82db0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made."

This seems to be due to cloudFlare's SSL certificate being SHA-1 signed; (more info at https://blog.cloudflare.com/cloudflare-and-sha-1-certificates/ )

Anyway, assuming that this is related, it seems that the CloudFlate SSL will cause UserVoice SDK to break for apps compiled for iOS9.

Can you please take a look?

Thanks, 
-Mike

**Comment by austintaylor** [comment]
Yeah we're looking into this. You can add an exception to your Info.plist in the meantime.

```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>uservoice.com</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
		</dict>
	</dict>
```

**Comment by ericnondahl** [comment]
Hi,
In my testing on the iOS 9 GM Seed, adding the above exception is not enough to make the uservoice SDK functional. Attempting to open a forum in the sdk results in a visible "Sorry, there was an error in the application." prompt and these logs:

<pre>015-09-11 16:07:00.123 RPG[442:53411] Error (HTTP connection failed): Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x13a07c710>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=<CFArray 0x13a0731f0 [0x19f116b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x1397ab840) s: ssl7911.cloudflare.com i: GlobalSign Organization Validation CA - G2>
	1 : <cert(0x1397aba90) s: GlobalSign Organization Validation CA - G2 i: GlobalSign Root CA>
)}, NSUnderlyingError=0x1397adbd0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, kCFStreamPropertySSLPeerCertificates=<CFArray 0x13a0731f0 [0x19f116b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x1397ab840) s: ssl7911.cloudflare.com i: GlobalSign Organization Validation CA - G2>
	1 : <cert(0x1397aba90) s: GlobalSign Organization Validation CA - G2 i: GlobalSign Root CA>
)}, _kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x13a07c710>, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., _kCFStreamErrorDomainKey=3, NSErrorFailingURLKey=https://dragonsoul.uservoice.com/api/v1/client.json, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSErrorFailingURLStringKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSErrorClientCertificateStateKey=0}
2015-09-11 16:07:00.131 RPG[442:53411] UserVoice SDK network error: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x13a07c710>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=<CFArray 0x13a0731f0 [0x19f116b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x1397ab840) s: ssl7911.cloudflare.com i: GlobalSign Organization Validation CA - G2>
	1 : <cert(0x1397aba90) s: GlobalSign Organization Validation CA - G2 i: GlobalSign Root CA>
)}, NSUnderlyingError=0x1397adbd0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, kCFStreamPropertySSLPeerCertificates=<CFArray 0x13a0731f0 [0x19f116b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x1397ab840) s: ssl7911.cloudflare.com i: GlobalSign Organization Validation CA - G2>
	1 : <cert(0x1397aba90) s: GlobalSign Organization Validation CA - G2 i: GlobalSign Root CA>
)}, _kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x13a07c710>, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., _kCFStreamErrorDomainKey=3, NSErrorFailingURLKey=https://dragonsoul.uservoice.com/api/v1/client.json, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSErrorFailingURLStringKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSErrorClientCertificateStateKey=0}
2015-09-11 16:07:00.158 RPG[442:53524] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
2015-09-11 16:07:00.167 RPG[442:53411] Error (HTTP connection failed): Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x1397b3050>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=<CFArray 0x1397857a0 [0x19f116b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x1397b0310) s: ssl7911.cloudflare.com i: GlobalSign Organization Validation CA - G2>
	1 : <cert(0x1397b2370) s: GlobalSign Organization Validation CA - G2 i: GlobalSign Root CA>
)}, NSUnderlyingError=0x1397809b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, kCFStreamPropertySSLPeerCertificates=<CFArray 0x1397857a0 [0x19f116b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x1397b0310) s: ssl7911.cloudflare.com i: GlobalSign Organization Validation CA - G2>
	1 : <cert(0x1397b2370) s: GlobalSign Organization Validation CA - G2 i: GlobalSign Root CA>
)}, _kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x1397b3050>, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., _kCFStreamErrorDomainKey=3, NSErrorFailingURLKey=https://dragonsoul.uservoice.com/api/v1/client.json, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSErrorFailingURLStringKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSErrorClientCertificateStateKey=0}
2015-09-11 16:07:00.171 RPG[442:53411] UserVoice SDK network error: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x1397b3050>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=<CFArray 0x1397857a0 [0x19f116b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x1397b0310) s: ssl7911.cloudflare.com i: GlobalSign Organization Validation CA - G2>
	1 : <cert(0x1397b2370) s: GlobalSign Organization Validation CA - G2 i: GlobalSign Root CA>
)}, NSUnderlyingError=0x1397809b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, kCFStreamPropertySSLPeerCertificates=<CFArray 0x1397857a0 [0x19f116b68]>{type = immutable, count = 2, values = (
	0 : <cert(0x1397b0310) s: ssl7911.cloudflare.com i: GlobalSign Organization Validation CA - G2>
	1 : <cert(0x1397b2370) s: GlobalSign Organization Validation CA - G2 i: GlobalSign Root CA>
)}, _kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x1397b3050>, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., _kCFStreamErrorDomainKey=3, NSErrorFailingURLKey=https://dragonsoul.uservoice.com/api/v1/client.json, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSErrorFailingURLStringKey=https://dragonsoul.uservoice.com/api/v1/client.json, NSErrorClientCertificateStateKey=0}
2015-09-11 16:07:00.321 RPG[442:53411] <CATransformLayer: 0x1397e4880> - changing property masksToBounds in transform-only layer, will have no effect
2015-09-11 16:07:00.322 RPG[442:53411] <CATransformLayer: 0x13a0a2080> - changing property masksToBounds in transform-only layer, will have no effect
2015-09-11 16:07:00.323 RPG[442:53411] <CATransformLayer: 0x13a08e930> - changing property masksToBounds in transform-only layer, will have no effect
</pre>

**Comment by gghanak** [comment]
Now that xCode7 and iOS9 are out ... is there an ETA on this issue?

**Comment by neybox** [comment]
Are there any updates regarding this issues? We are experiencing complaints from our iOS 9 users.

**Comment by ericnondahl** [comment]
As a workaround, I've just redirected our iOS 9 users to the website while we wait for a fix.

**Comment by jhhall63** [comment]
I ran across this, thought it might help: https://forums.developer.apple.com/thread/9029

**Comment by dbgrandi** [comment]
Looks like this is fixed now.

**Comment by gghanak** [comment]
Not fully fixed yet - all images in KB Articles are being blocked because they are insecure even if inserted via an upload...

**Comment by paulz** [comment]
Here are the settings that worked for me including loading of images in KB articles:
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<false/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>uservoice.com</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionMinimumTLSVersion</key>
				<string>TLSv1.2</string>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```
taken from http://stackoverflow.com/a/31694233 with the addition of ```NSIncludesSubdomains```

**Comment by gghanak** [comment]
Not for me, KB articles are still a dud...

**Comment by austintaylor** [comment]
We have updated our certificates to SHA-256. Everything seems to be working again.

**Comment by gghanak** [comment]
When I open a KB Article with images, for each image it does the following error and fails to show it:
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

**Comment by austintaylor** [comment]
@gghanak So as far as I can tell, images hosted by UserVoice are all served over ssl. If you have a counter-example, please send me a link to the article. If we have http urls in some articles we might could just do a find-replace.

Some images give me the "HTTP load failed" message in the simulator even though they are served over https, but they work fine on a device. I think this has something to do with root certs.

If you are hosting your images elsewhere, you should probably add an exception.

**Comment by gghanak** [comment]
@austintaylor Those KB articles I've tested were calling images with https:// on a uservoice.com subdomain. I did test this on an iOS 9.0.1 iPhone Plus S device (not a simulator) - several times - on LTE and Wifi... seems like something is still a miss.

**Comment by austintaylor** [comment]
@gghanak Could you send me a link to one such article? I haven't been able to repro on device.

**Comment by gghanak** [comment]
@austintaylor It seems that the problem is that the uservoice uploaded images are actually located on amazon servers, when I follow the asset URL it redirects to: https://s3.amazonaws.com/uploads.uservoice.com/assets which has only 128bit encryption also...
